name: Run .NET Tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore
        
      - name: Run tests
        continue-on-error: true
        run: dotnet test --no-build --verbosity normal
